export const GET_ITEMS = 'GET_ITEMS';
export const GET_ITEM = 'GET_ITEM';
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const ADD_SUCCESS = 'ADD_SUCCESS';
export const GET_RANDOM_ITEMS = 'GET_RANDOM_ITEMS';
export const RESET_LOADINGITEMS = 'RESET_LOADINGITEMS';
export const RESET_SELECTEDITEM = 'RESET_SELECTEDITEM';
